# Generated by Django 5.1.4 on 2024-12-22 05:37

from django.db import migrations
from datetime import datetime

def cargar_datos(apps, schema_editor):
    Departamento = apps.get_model('MVC', 'Departamento')
    Empleado = apps.get_model('MVC', 'Empleado')
    Gasto = apps.get_model('MVC', 'Gasto')

    # Crear departamentos
    depto_it = Departamento.objects.create(nombre="IT")
    depto_desarrollo = Departamento.objects.create(nombre="Desarrollo")
    depto_diseno = Departamento.objects.create(nombre="Diseño")
    depto_marketing = Departamento.objects.create(nombre="Marketing")

    # Crear empleados
    empleado_1 = Empleado.objects.create(nombre="Zoila Baca")
    empleado_2 = Empleado.objects.create(nombre="Aquiles C")
    empleado_3 = Empleado.objects.create(nombre="Johnny Melas")

    # Crear gastos
    Gasto.objects.create(empleado=empleado_1, departamento=1, descripcion="UPS", monto=60, fecha=datetime(2024, 11, 16))
    Gasto.objects.create(empleado=empleado_3, departamento=2, descripcion="Monitor secundario", monto=250, fecha=datetime(2024, 11, 22))
    Gasto.objects.create(empleado=empleado_3, departamento=3, descripcion="Rollup", monto=60, fecha=datetime(2024, 11, 23))
    Gasto.objects.create(empleado=empleado_1, departamento=1, descripcion="UPS", monto=60, fecha=datetime(2024, 11, 25))

class Migration(migrations.Migration):

    dependencies = [
        ('MVC', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_datos),
    ]
