# Generated by Django 5.1.4 on 2024-12-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVC', '0002_auto_20241222_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.AddField(
            model_name='gasto',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MVC.departamento'),
            preserve_default=False,
        ),
    ]
